PIMS-77: Add filter to SPL view of projects
bcgov/PIMS pull request #1223
Opened 2022-03-21 19:31 UTC by LawrenceLau2020

changes to the property filters and typeahead component.

2022-03-21 19:32 UTC, LawrenceLau2020 commented on frontend/src/components/common/form/ParentSelect.tsx
> +
Thanks for your help on this one, Jeremy, it definitely wasn't an easy fix!

2022-03-21 19:49 UTC, Fosol requested changes

2022-03-21 19:49 UTC, Fosol commented on frontend/src/features/projects/list/ProjectApprovalRequestListView.tsx
> +      defaultFilter={{ statusId: ['7,8'] }}
Fix the array values.

2022-03-22 22:10 UTC, Fosol approved these changes

2022-03-23 15:01 UTC, merged