PIMS-225 and 226: replace the wms PMBC layer and autopopulate the legal description
bcgov/PIMS pull request #1707
Opened 2023-09-18 22:21 UTC by LawrenceLau2020

## 🎯 Summary

  
[PIMS-225: ](https://citz-imb.atlassian.net/browse/PIMS-225)
[PIMS-226: ](https://citz-imb.atlassian.net/browse/PIMS-226)

Replaced the pmbc parcel layer with the "public one" which doesn't include the "legal description" field.
Needed to create new functions to get the legal description from the LTSA api.
We seem to be missing the "survey designation" information, doesn't seem to be part of the order information from LTSA.

## 🔰 Checklist

- [x] I have read and agree with the following checklist and am following the guidelines in our [Code of Conduct](CODE_OF_CONDUCT.md) document.

> - I have performed a self-review of my code.
> - I have commented my code, particularly in hard-to-understand areas.
> - I have made corresponding changes to the documentation where required.
> - I have tested my changes to the best of my ability.
> - My changes generate no new warnings.

2023-09-18 22:22 UTC, LawrenceLau2020 commented on frontend/src/features/properties/hooks/useParcelLayerData.tsx
> +  const [ltsa, setLtsa] = useState<ILTSAOrderModel | undefined>(undefined);
I'm not sure we even need the state?

2023-09-18 22:25 UTC, LawrenceLau2020 commented
I tried breaking out the "getLTSAData" into a new hook/function, but was running into issues.

2023-09-18 22:27 UTC, LawrenceLau2020 commented on frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContent.tsx
>    const getLTSAData = async () => {
maybe we can break this function out into a "reusable" component.....instead of having it in 2 files.

2023-09-19 17:19 UTC, dbarkowsky requested changes

2023-09-19 17:19 UTC, dbarkowsky commented on frontend/src/features/properties/hooks/useParcelLayerData.tsx
> +  };
Agree with you that we don't really need the state. Could just do this here. Plus some other changes seen below.
```suggestion
const api = useApi();
```

2023-09-19 17:19 UTC, dbarkowsky commented on frontend/src/features/properties/hooks/useParcelLayerData.tsx
> +          const ltsaResponseData = await getLTSAData(pid);
Then we would only need...
```suggestion
          const ltsaResponseData = await api.getLTSA(pid);
```

2023-09-19 17:19 UTC, dbarkowsky commented on frontend/src/features/properties/hooks/useParcelLayerData.tsx
> +  }, [formikRef, getByType, parcelId, parcelLayerData, ltsa]);
And we shouldn't need this
```suggestion
  }, [formikRef, getByType, parcelId, parcelLayerData]);
```

2023-09-19 17:19 UTC, dbarkowsky commented on frontend/src/features/properties/hooks/useParcelLayerData.tsx
> +  const [ltsa, setLtsa] = useState<ILTSAOrderModel | undefined>(undefined);
Agreed. See below comment.

2023-09-19 19:51 UTC, dbarkowsky approved these changes
Noting that we haven't met the test threshold for this change.
Other than that, I don't see any issues. 
Tested adding a new parcel and using the parcel popup.

2023-09-19 20:26 UTC, merged